version: '3'

services:
  mysql_principal:
    container_name: Maestro
    image: mysql:8.0
    ports:
      - 3306:3306
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=replica
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: informacion
    volumes:
      - master_datos:/var/lib/mysql

  mysql_secundario:
    container_name: Esclavo
    image: mysql:8.0
    ports:
      - 3307:3306
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=replica
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: informacion
    volumes:
      - slave_datos:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      PMA_HOSTS: "mysql_principal,mysql_secundario"
      PMA_ARBITRARY: 1 

  python:
    build:
      context: ./web1
      dockerfile: Dockerfile
    container_name: ServidorWeb1
    ports:
      - 3308:5000

  python1:
      build:
        context: ./web2
        dockerfile: Dockerfile
      container_name: ServidorWeb2
      ports:
        - 3309:5000

  nginx:
      build:
        context: ./nginx
        dockerfile: Dockerfile
      container_name: nginx
      ports:
        - 8080:80
      

volumes:
  master_datos:
  slave_datos:   