events { }
http {
    upstream servidores{
        #ip_hash; #responder ip
        #servicios deocker compose

        server python:5000 weight=5;
        server python1:5000 weight=5;
    } 

    server{
        listen 80;
        location /{
            proxy_pass http://servidores;
        }
    }
}